#base image
FROM alpine:3.16.0
RUN apk add --no-cache java-cacerts openjdk17-jdk
RUN apk --no-cache add gradle
RUN apk add --no-cache make
COPY code/ /code/
WORKDIR /code/
CMD ["tail", "-f", "/dev/null"]